## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 530869413@qq.com
    password:  cbxqelrrblbacbba
    properties.mail.smtp.port: 587
    from: 530869413@qq.com
abc:
  config: 34566
